<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:HelloDevops"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="urn:HelloDevops"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:weo="http://www.example.org">
  <types>
    <xsd:schema targetNamespace="urn:HelloDevops/types"
                elementFormDefault="qualified"/>
    <xsd:schema>
      <xsd:import schemaLocation="../../../xsd/HelloDevopsSchema.xsd"
                  namespace="http://www.example.org"/>
    </xsd:schema>
  </types>
  <portType name="getHelloDevops">
    <operation name="RequestOperation">
      <input message="tns:getHelloDevops_Request"/>
      <output message="tns:getHelloDevops_Response"/>
    </operation>
  </portType>
  <message name="getHelloDevops_Request">
    <part name="part" element="weo:Request"/>
  </message>
  <message name="getHelloDevops_Response">
    <part name="part" element="weo:Response"/>
  </message>
  <binding name="getHelloDevopsSOAP12Binding" type="tns:getHelloDevops">
    <soap12:binding style="document"
                    transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="RequestOperation">
      <soap12:operation style="document"
                        soapAction="urn:HelloDevops/RequestOperation"/>
      <input>
        <soap12:body use="literal" parts="part"/>
      </input>
      <output>
        <soap12:body use="literal" parts="part"/>
      </output>
    </operation>
  </binding>
  <service name="getHelloDevops">
    <port name="getHelloDevopsPort" binding="tns:getHelloDevopsSOAP12Binding">
      <soap12:address location="http://www.example.com"/>
    </port>
  </service>
</definitions>
