<?xml version="1.0" encoding="UTF-8"?>
<con:xqueryEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:xquery><![CDATA[declare namespace ns0 = "http://xmlns.tigo.com/Test/Devops/ManagePostSaleComplain/schema";
declare namespace ns1 = "http://xmlns.tigo.com/ManagePostSaleComplain/schema";
declare namespace do = "http://tempuri.org/Test/Devops/ManagePostSaleComplain/XQUERY/ManagePostSaleComplain/";

declare function do:ManagePostSaleComplain()
    {
        <ns0:ManagePostSaleComplainResponse>
            <ns0:ResponseBody>
            
                    <ns0:otId> 2 </ns0:otId>
                     <ns0:Result>Demo POC Despliegue Remoto </ns0:Result>
              
            </ns0:ResponseBody>
        </ns0:ManagePostSaleComplainResponse>
};



do:ManagePostSaleComplain()]]></con:xquery>
</con:xqueryEntry>